circleci pipeline
LBHackney-IT/mtfh-search-microfrontend pull request #2
Opened 2021-03-25 12:32 UTC by humulla

- [x]  build and deploy job for dev, staging and production
        this included unit test command

- [ ] Need to add the S3 bucket sync once terraform for them have been created

2021-03-25 13:06 UTC, LBHMGeorgieva commented on .circleci/config.yml
> +           assume-role-development:
Indentation needs to be fixed here

2021-03-25 13:06 UTC, LBHMGeorgieva commented on .circleci/config.yml
> +    executor: fss-executor
The executor name needs to be amended

2021-03-25 13:07 UTC, LBHMGeorgieva commented on .circleci/config.yml
> +    executor: fss-executor
Executor name needs to be changed

2021-03-25 13:07 UTC, LBHMGeorgieva commented on .circleci/config.yml
> +    executor: fss-executor
Executor name needs to be changed

2021-03-25 13:10 UTC, LBHMGeorgieva requested changes
Please have a look at some of the comments I left. Also, the step to deploy to S3 is missing. I would suggest you separate the run tests command as a separate job, and in the build and deploy job, run the build command and deploy to S3. Lastly, please add a job for deploying the terraform resources.

2021-03-25 16:24 UTC, LBHMGeorgieva commented on .circleci/config.yml
> +      - install-dependencies
We should run the tests after the dependencies are installed, but before we proceed with assuming the role and applying terraform

2021-03-25 16:24 UTC, LBHMGeorgieva commented on .circleci/config.yml
> +          to: 's3://lbh-housing-tenancy-lease-frontend-development.hackney.gov.uk/'
Bucket name needs to change to reflect environment

2021-03-25 16:24 UTC, LBHMGeorgieva commented on .circleci/config.yml
> +          to: 's3://lbh-housing-tenancy-lease-frontend-development.hackney.gov.uk/'
Bucket name needs to change to reflect environment

2021-03-26 08:07 UTC, humulla commented on .circleci/config.yml
> +      - install-dependencies
`run tests` should require `build-deploy-development` to pass right? 
if so, would `build-deploy-development `be after `install-dependencies` and then `run-tests`?

2021-03-26 15:06 UTC, LBHMGeorgieva commented on .circleci/config.yml
> +          context: api-assume-role-housing-development-context
You don't need to pass the context here

2021-03-26 15:07 UTC, LBHMGeorgieva commented on .circleci/config.yml
> +            - install-dependencies
maybe change this to be requires run-tests

2021-03-26 15:39 UTC, LBHMGeorgieva commented on .circleci/config.yml
> +            - assume-role-development
This should be requires :  terraform-init-and-apply-to-development

2021-03-29 12:51 UTC, LBHMGeorgieva approved these changes

2021-03-29 12:55 UTC, merged